# 20240603
# filename:  input.toml
# 圆柱绕流，不符合理论解，只具有观赏性
# 达到稳定脱落状态需要迭代约20000步
# 脱落频率不符合理论公式。可能是因为没有湍流模型或者网格没有边界层
# 注意卡门涡街出现与否，跟马赫数、尺度、雷诺数都有很大关系
# 

[basic]
continue = true
dimension = 2
filename = "cylinder_allfar_50" 
meshFileType = "su2" 
useGPU = 1                      # 0-CPU 1-GPU
isDebugMode = false

[constant]
T0 = 288.16                     # 海平面温度参考
p0 = 101325.0                   # 海平面压力参考
Re = 6.5e6
Pr = 0.73
gamma = 1.4
referenceArea = 1               # (三维算例)参考面积，或(二维算例)参考弦长
mesh_scale_factor = 1           # 网格缩放因子
calculate_mu0_by_Re = true      # true: 以Re为基准 false: 以mu0为基准

[initialCondition]
type = 1                        # 1-inf均匀流 2-等熵涡 3-激波管 4-双马赫反射

[boundaryCondition.2D.inf]
input_mode = 0                  # 0-{Ma,AoA} 1-{rho,u,v,p} 2-{rho,rhou,rhov,rhoE} 3-{rho, u, angle_degree, p}
Ma = 0.5
AoA = 0

[output]
step_per_print = 50
step_per_output_field = 500
step_per_output_hist = 500
start_output_field = 30000      # 从什么时候开始输出流场
maxIteration = 40000            # 
tolerace_residual = 1e-7        # 残差低于此值认为达到稳态

[output.output_var]
rho = true
u = true
v = true
p = true

[physicsModel]
equation = 2                    # 1-Euler,2-NS

[time]
is_steady = 0                   # 0-非定常 1-定常
is_explicit = 1                 # 0-隐式   1-显式
CFL = 2.2
CFL_steady = 0.8
max_physical_time = 200         # max_physical_time = 2.255788
time_advance = 3101             # 3101-显式单步推进，3103-RK3

[inviscid_flux_method]
flag_reconstruct = 3002         # 3001-常量重构 3002-线性重构 3003-MUSCL插值
flag_gradient = 2               # 1-最小二乘 2-GreenGauss
flux_conservation_scheme = 2002 # 2001-LocalLaxFriedrichs, 2002-Roe
flux_limiter = 1                # 0-none 1-barth 2-minmod 3-vanleer
